### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by amarhr23** [bhaireshm/extract-languages#1]
Hi @bhaireshm,

This is a great package to use! I noticed that when we want to ignore a folder, we currently need to specify each exclusion individually (el -i .venv). Since almost every project includes a .gitignore file, could you consider adding support for automatically ignoring files and folders listed there in future releases?

Thank you!

**Comment by bhaireshm** [comment]
Hi @amarhr23, thank you for the request.

Above requested feature is implemented in the new version `v1.1.1`, update to latest version and try it out. 🚀
